### ISSUE TITLE
The client is missing the following tls attributes: tlsCertificateFilePath, tlsKeyFilePath

### ISSUE THREAD

**Issue by xuanyangyang** [spring-projects/spring-pulsar#374]
The client is missing the following tls attributes: tlsCertificateFilePath, tlsKeyFilePath

see:
https://pulsar.apache.org/docs/2.11.x/security-tls-transport/#configure-clients
![image](https://user-images.githubusercontent.com/19355674/226095742-d3fff636-10eb-4b41-89d9-a98c7727ced5.png)

**Comment by onobc** [comment]
Hi @xuanyangyang ,
Those configuration properties are available but they are rooted under `spring.pulsar.client.authentication` rather than `spring.pulsar.client` as we currently consider them properties of the TLS auth plugin. 

The auth area of Pulsar was in flux between 2.10 and 2.11 a bit so we have left this part of the framework alone until things settled down a bit. We have https://github.com/spring-projects-experimental/spring-pulsar/issues/96 to circle back in this area. 

Please see https://docs.spring.io/spring-pulsar/docs/current-SNAPSHOT/reference/html/#client-authentication and then expand the `"Click here for Tls"`.  

The example looks like: 
```yaml
spring:
  pulsar:
    client:
      auth-plugin-class-name: org.apache.pulsar.client.impl.auth.AuthenticationTls
      authentication:
        tls-cert-file: /path/to/my-role.cert.pem
        tls-key-file: /path/to/my-role.key-pk8.pem
      enable-tls: true
      tls-trust-certs-file: /path/to/cacert.pem

```

Let me know if you are good w/ closing this issue out in light of the above info.

Thanks. 

P.S. If you have not starred the repo yet and you are enjoying using it so far, please star it if you don't mind 😸

**Comment by KevinLiLu** [comment]
@onobc Can we separate the mTLS configurations from the authentication plugin? Pulsar currently allows you to enable mTLS without any authentication plugin:
```
PulsarClient client = PulsarClient.builder()
    .serviceUrl("pulsar+ssl://broker.example.com:6651/")
    .tlsKeyFilePath("/path/to/client.key-pk8.pem")
    .tlsCertificateFilePath("/path/to/client.cert.pem")
    .tlsTrustCertsFilePath("/path/to/ca.cert.pem")
    .enableTlsHostnameVerification(false) // false by default, in any case
    .allowTlsInsecureConnection(false) // false by default, in any case
    .build();
```

Sample use-cases:
1. We use mTLS but don't need any authentication plugin (`authenticationEnabled=false` in broker)
2. We use mTLS and use some other authenticator (ex. Kerberos)

We could support this in the current codebase by adding the configs at the `spring.pulsar.client` level.

PEM approach:
```
spring:
  pulsar:
    client:
      # Existing configs
      use-tls: true
      tls-trust-certs-file: /path/to/ca.cert.pem

      # new PEM configs required
      tls-cert-file: /path/to/client.cert.pem
      tls-key-file: /path/to/client.key-pk8.pem
```

KeyStore approach:
```
spring:
  pulsar:
    client:
      # Existing configs
      use-tls: true
      use-key-store-tls: true
      tls-trust-store-password: password
      tls-trust-store-path: /path/to/client.truststore.jks
      tls-trust-store-type: JKS

      # New KeyStore configs required
      tls-key-store-password: password
      tls-key-store-path: /path/to/client.keystore.jks
      tls-key-store-type: JKS
```

I'm willing to give it a try and raise a PR if this sounds good 😃
