### ISSUE TITLE
Migrate Release GHA workflow to the Changelog Generator Action

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-pulsar#856]
Instead of `curl -sSL -O https://github.com/spring-io/github-changelog-generator/releases/download/v0.0.10/github-changelog-generator.jar`, there is now a GH Action for its functionality: 
For example: https://github.com/spring-io/github-changelog-generator?tab=readme-ov-file#using-as-a-github-action
```
      - name: Generate Changelog
        uses: spring-io/github-changelog-generator@v0.0.11
        with:
          milestone: ${{ env.MILESTONE }}
          token: ${{ env.GITHUB_TOKEN }}
          config-file: changelog.properties
```
