### ISSUE TITLE
Migrate aways from third-party (not varified publisher) actions

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-pulsar#857]
For example, this one is no: `julb/action-post-googlechat-message`.
There is a simple replacement though:
```
      - name: Announce Release in Chat
        if: env.CHAT_WEBHOOK_URL
        run: |
          curl -X POST '${{ env.CHAT_WEBHOOK_URL }}' -H 'Content-Type: application/json' -d '{ text: "${{ github.event.repository.name }}-announcing `${{ env.MILESTONE }}`"}'
        env:
          CHAT_WEBHOOK_URL: ${{ secrets.SPRING_RELEASE_CHAT_WEBHOOK_URL }}
```

You can take ideas from the: https://github.com/spring-io/spring-github-workflows/blob/main/.github/workflows/spring-finalize-release.yml
