### ISSUE TITLE
PHASE 2: Make client authentication simpler

### ISSUE THREAD

**Issue by onobc** [spring-projects/spring-pulsar#96]
Provide 1st class properties for each type of supported auth (`spring.pulsar.client.auth.<type>.*`). The auto-config will then craft the appropriate .auth. object and set it on the client builder using the .auth.)` method. 

#### TLS
```yaml
spring.pulsar.client:
  tlsTrustCertsFile: ...
 .auth.tls:
    tlsCertFile: ...
    tlsKeyFile: ...
```

#### Athenz
```yaml
spring.pulsar.client:
  tlsTrustCertsFile: ...
 .auth.athenz:
    tenantDomain: ...
    tenantService: ...
    providerDomain: ...
    privateKey: ...
    keyId: ..
```

#### Kerberos
```yaml
spring.pulsar.client.auth.kerberos:
  saslJaasClientSectionName: ...
  serverType: ...
```

#### OAuth2
```yaml
spring.pulsar.client.auth.oauth2:
  issuerUrl: ... 
  credentialsUrl: ...
  audience: ...
```

#### Http Basic
```yaml
spring.pulsar.client.auth.basic:
  userId: ...
  password: ...
```

#### JWT 
```yaml
spring.pulsar.client.auth.jwt:
  token: ...
```
